#!/usr/bin/env bash
# Install nginx

new_conf="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt update
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
sudo service nginx restart