#!/usr/bin/env bash
# Install nginx

new_conf="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sed -i "26i $new_conf" /etc/nginx/sites-available/default
service nginx restart