#!/usr/bin/env bash
# Install nginx

new_conf="server_name _;\n\rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sed -i "s|server_name\ _;/$new_conf/g" /etc/nginx/sites-available/default
sudo service nginx restart