#!/usr/bin/env bash
# Install nginx

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}"
sed -i "27i $newlines" /etc/nginx/sites-available/default
service nginx restart