#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
echo "
frontend http
	bind *:80
	mode http
	default_backend web-backend
	backend web-backend

balance roundrobin
	server 3507-web-01 34.73.110.10:80 check
	server 3507-web-02 54.234.193.97:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
service haproxy restart
