#!/usr/bin/env bash
#switch case from 1 - 20
iter=0
while [ $iter -le 20 ]
do
	echo $iter
	case $iter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((iter++))
done
